#!/usr/bin/env bash

if [ $# -eq 0 ]; then
	xargs "$0"
else
	for arg in "$@"; do
		if [ ! -d "$c/$arg" ]; then
			echo "Module not found: $c/$arg" >&2
			continue
		fi

		pushd "$c/$arg"
		hub create && git remote rename origin upstream && git push upstream master
		popd
	done
fi
