#!/usr/bin/env bash

tar="$1"
shift

echo "Untar: $tar"
tar xf "$tar"
dir="$(tar tf "$tar" | head -n 1)"
cd "$dir"
echo "dir: $PWD"

./configure --prefix="$HOME" "$@" && echo "configured" && make && echo "made" && make install
